---
abstract: 'a native attribute trait for enums'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: 0.92
  Types::Standard: 0.008
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.015, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Enumeration
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Moose::Meta::Attribute::Custom::Trait::Enum:
    file: lib/Moose/Meta/Attribute/Custom/Trait/Enum.pm
    version: 0.002
  Moose::Meta::Attribute::Custom::Trait::Enumeration:
    file: lib/Moose/Meta/Attribute/Custom/Trait/Enumeration.pm
    version: 0.002
  MooseX::Enumeration:
    file: lib/MooseX/Enumeration.pm
    version: 0.002
  MooseX::Enumeration::Meta::Attribute::Native::Trait::Enumeration:
    file: lib/MooseX/Enumeration/Meta/Attribute/Native/Trait/Enumeration.pm
    version: 0.002
  MooseX::Enumeration::Meta::Method::Accessor::Native::Enumeration::is:
    file: lib/MooseX/Enumeration/Meta/Method/Accessor/Native/Enumeration/is.pm
    version: 0.002
requires:
  Moose: 1.15
  Type::Tiny::Enum: 0.030
  perl: 5.008001
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/MooseX-Enumeration/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=MooseX-Enumeration
  homepage: https://metacpan.org/release/MooseX-Enumeration
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-moosex-enumeration.git
version: 0.002
